### ISSUE TITLE
Access token has to be manually refreshed at every startup

### ISSUE THREAD

**Issue by cuaroc98** [aleab/toastify#114]
With Facebook I have to authenticate Toastify everytime my pc starts up

## EXPECTED BEHAVIOUR
Only authenticate once

## ACTUAL BEHAVIOUR
Have to authenticate every time the pc starts up

## STEPS TO REPRODUCE THE BEHAVIOUR
- start toastify
- authenticate with facebook
- log out of facebook
- restart pc
- start toastify

## LOG FILE
*(Drag and drop your `Toastify.log` file here; it can be found in `%LocalAppData%\Toastify`)*

**Comment by cuaroc98** [comment]
Sorry I forgot the log file, here it is:


08:51:39.581+01:00 INFO  [Toastify.EntryPoint.LogSystemInfo, 144] (1) – :: ====================================================================== ::
08:51:39.596+01:00 INFO  [Toastify.EntryPoint.LogSystemInfo, 144] (1) – :: [Architecture] IntPtr: 64bit, Is64BitProcess: True, Is64BitOS: True    ::
08:51:39.596+01:00 INFO  [Toastify.EntryPoint.LogSystemInfo, 144] (1) – :: [OS] Version: 10.0.17763, Friendly Name: "Microsoft Windows 10 Pro"    ::
08:51:39.596+01:00 INFO  [Toastify.EntryPoint.LogSystemInfo, 144] (1) – :: [.NET] CLR Version: 4.0.30319.42000, Framework Version: 4.7.2 or later ::
08:51:39.596+01:00 INFO  [Toastify.EntryPoint.LogSystemInfo, 144] (1) – :: [Toastify] Version: 1.11.1.31247, [Spotify] Version: 1.1.0.237         ::
08:51:39.596+01:00 INFO  [Toastify.EntryPoint.LogSystemInfo, 144] (1) – :: ====================================================================== ::
08:51:39.876+01:00 WARN  [Toastify.Model.ToastifyActionRegistry.GetOrAddAction, 133] (1) – Unhandled toastify action enum value: CopyTrackInfo
08:51:39.876+01:00 WARN  [Toastify.Model.ToastifyActionRegistry.GetOrAddAction, 133] (1) – Unhandled toastify action enum value: PasteTrackInfo
08:51:40.298+01:00 INFO  [Toastify.Core.Spotify.GetSpotifyPath, 286] (1) – Spotify executable found: "C:\Users\Paul Kothmair\AppData\Roaming\Spotify\Spotify.exe"
08:51:42.064+01:00 WARN  [Toastify.Core.SpotifyWebAPI.LogReturnedValueIfError, 164] (14) – Couldn't get the current playback context. Returned value = {
   StatusCode: "NoContent"
}
10:11:48.403+01:00 WARN  [Toastify.Core.SpotifyWebAPI.LogReturnedValueIfError, 164] (13) – Couldn't get the current playback context. Returned value = {
   StatusCode: "Unauthorized",
   Error: {
      Status: 401,
      Message: "The access token expired"
   }
}
10:11:48.419+01:00 ERROR [Toastify.Core.Spotify+<SpotifyWindowTitleWatcher_TitleChanged>d__105.MoveNext, 855] (13) – Unhandled exception in SpotifyWindowTitleWatcher_TitleChanged.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Toastify.Model.CurrentlyPlayingObject..ctor(PlaybackContext playbackContext) in E:\Users\Alessandro\Documents\Visual Studio 2017\Projects\Toastify\toastify\Toastify\src\Model\CurrentlyPlayingObject.cs:line 57
   at Toastify.Core.SpotifyWebAPI.<GetCurrentlyPlayingTrackAsync>d__14.MoveNext() in E:\Users\Alessandro\Documents\Visual Studio 2017\Projects\Toastify\toastify\Toastify\src\Core\SpotifyWebAPI.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Toastify.Core.Spotify.<UpdateTrackInfoUsingWebApi>d__81.MoveNext() in E:\Users\Alessandro\Documents\Visual Studio 2017\Projects\Toastify\toastify\Toastify\src\Core\Spotify.cs:line 565
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Toastify.Core.Spotify.<SpotifyWindowTitleWatcher_TitleChanged>d__105.MoveNext() in E:\Users\Alessandro\Documents\Visual Studio 2017\Projects\Toastify\toastify\Toastify\src\Core\Spotify.cs:line 855
10:12:00.103+01:00 WARN  [Toastify.Core.SpotifyWebAPI.LogReturnedValueIfError, 164] (14) – Couldn't get the current playback context. Returned value = {
   StatusCode: "Unauthorized",
   Error: {
      Status: 401,
      Message: "The access token expired"
   }
}

**Comment by Vankog** [comment]
dito

**Comment by hartmark** [comment]
+1

**Comment by fragande** [comment]
This may solve your issue, it did for me: https://github.com/aleab/toastify/issues/111#issuecomment-528974604
