### ISSUE TITLE
some project help

### ISSUE THREAD

**Issue by Vankog** [aleab/toastify#27]
Hey, 

I am currently in the process of setting up the project in VS.
However, there are some issues I'd like to resolve. 
1. The NuGet packages were automatically installed.
1. I ran the Analytics template and added some fake IDs for time being.
1. Upon starting the app I get a break on on Win32API.cs on line 215:  
```text
System.EntryPointNotFoundException
  HResult=0x80131523
  Message=Unable to find an entry point named 'GetWindowLongPtr' in DLL 'user32.dll'.
  Source=Toastify
  StackTrace:
   at Toastify.Win32API.GetWindowLongPtr(IntPtr hWnd, GWL nIndex)
   at Toastify.Win32API.AddWindowLongPtr(IntPtr hWnd, GWL nIndex, IntPtr dwLong) in C:\Users\danie\Documents\VSProjects\Toastify\Toastify\src\Win32API.cs:line 215
   at Toastify.Win32API.AddToolWindowStyle(IntPtr hWnd) in C:\Users\danie\Documents\VSProjects\Toastify\Toastify\src\Win32API.cs:line 222
   at Toastify.View.ToastView.Window_Loaded(Object sender, RoutedEventArgs e) in C:\Users\danie\Documents\VSProjects\Toastify\Toastify\src\View\ToastView.xaml.cs:line 716
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```   
1. I continue this, but the the program crashes:  
    dialog 1:   
```text
---------------------------
Unhandled exception
---------------------------
Unhandled Dispatcher exception.
Unable to find an entry point named 'GetWindowLongPtr' in DLL 'user32.dll'.
---------------------------
OK   
---------------------------
```   
    dialog 2:   
```text
---------------------------
Unhandled exception
---------------------------
Unhandled top-level exception.
Unable to find an entry point named 'GetWindowLongPtr' in DLL 'user32.dll'.
---------------------------
OK   
---------------------------
```

It's been about a decade since my last usage of C#. I will take some refresher courses to get up to date and Toastify will be my practice object. ;-)

**Comment by aleab** [comment]
The problem is that Toastify is loading the 32 bit version of user32.dll, which doesn't have that particular function. The solution is to select the "x64" platform configuration in Visual Studio, instead of the "AnyCPU" one.

![](https://vgy.me/vV9MIq.png)

**Comment by Vankog** [comment]
OK, it seems I need an issue as means to discuss code parts or ask questions. So I just take this one.

https://github.com/aleab/toastify/blob/09ec085ff7ae246e2c7a531353e07e5e11690aa5/Toastify/src/Model/KeyOrButton.cs#L38
Is there any reason to keep this constructor? It seems superfluid and messy to me in comparison to the two simple constructors and I don't see any callers besides your test case.

**Comment by aleab** [comment]
Unfortunately there is: that's the constructor used by the json deserializer. I didn't want to make the properties' setters public for it, so that constructor is really necessary.

**Comment by aleab** [comment]
Also, I've just created this public chat room: https://gitter.im/aleab-toastify.
We could move every conversation/discussion there maybe, I think it's better not to abuse Github's issues for that.
