### ISSUE TITLE
Error launching toastify

### ISSUE THREAD

**Issue by baseballbrad3** [aleab/toastify#29]
I'm getting an error when launching Toastify. I get it on the new 1.10.1 release as well as the previous 1.10.0. I'm using the ~~Windows~~ Microsoft Store version of Spotify.

Here are the logs that I was able to dig up. I couldn't figure out how to enable Debug level logs though.

Any idea what I can do to fix it?

```
15:45:52,766-06:00 WARN  [Toastify.Model.Settings.XmlSerializer_UnknownElement, 0] (1) � XmlSerializer: unknown element found [PreventSleepWhilePlaying]
15:45:55,795-06:00 INFO  [Toastify.EntryPoint.RunApp, 0] (1) � Architecture: IntPtr = 64bit, Is64BitProcess = True, Is64BitOS = True
15:45:55,796-06:00 INFO  [Toastify.EntryPoint.RunApp, 0] (1) � Toastify version = 1.10.1.33442
15:45:56,181-06:00 INFO  [Toastify.Core.Spotify.GetSpotifyPath, 0] (1) � Spotify executable found: "shell:AppsFolder\SpotifyAB.SpotifyMusic_zpdnekdrzrea0!Spotify"
15:45:56,196-06:00 INFO  [Toastify.Core.Spotify.LaunchSpotifyAndWaitForInputIdle, 0] (4) � Launching Spotify...
15:45:58,259-06:00 INFO  [Toastify.Core.Spotify.LaunchSpotifyAndWaitForInputIdle, 0] (4) � Spotify process started: System.Diagnostics.Process (Spotify)
15:45:58,264-06:00 INFO  [Toastify.Core.Spotify.ConnectWithSpotify, 0] (4) � Connecting to Spotify's local APIs endpoint...
15:45:58,788-06:00 ERROR [Toastify.Core.Spotify.StartSpotify_WorkerTaskCompleted, 0] (1) � Unknown error while starting Spotify.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at SpotifyAPI.Local.RemoteHandler.GetOAuthKey()
   at SpotifyAPI.Local.RemoteHandler.Init()
   at Toastify.Core.Spotify.ConnectWithSpotify(DoWorkEventArgs e)
   at Toastify.Core.Spotify.StartSpotify_WorkerTask(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by aleab** [comment]
Hi @baseballbrad3, thanks for the issue report.

It's currently not possible to enable Debug level logs on the user side, since the logger's configuration file is embedded in the binary file (and I prefer keeping it there); I might add some command line parameters in the new version though.
Anyway, I don't think Debug logs would have been useful in this case, since the issue seems to reside in one of the libraries I'm using, SpotifyAPI-NET. I don't have any clue on what is causing it, though.

Do you mind opening [this URL](http://open.spotify.com/token) in a browser and see if it returns a valid JSON string?
If it doesn't, try using [Postman](https://www.getpostman.com/) (or something similiar) to send a GET request to that address with the `UserAgent` header value set to `Spotify (1.0.50.41368.gbd68dbef)`; if it still doesn't return anything meaningful, try with your version of Spotify instead of `1.0.50.41368.gbd68dbef`.

**Comment by baseballbrad3** [comment]
Bah, looks like there was a firewall rule blocking open.spotify.com. I switched to a less restricted network and it popped right up. Looks like it was all on my end. Thanks for the help.
